name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Konfigurasi Git Identity (Diperlukan untuk commit penghapusan)
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # 2. BERSIH-BERSIH KHUSUS HUGGING FACE
          # Kita hapus folder frontend karena HF cuma butuh backend.
          # Dengan dihapus, maka file gambar binary pun ikut hilang -> HF Senang!
          rm -rf frontend-react
          
          # Hapus juga .gitattributes agar tidak ada aturan LFS yang tersisa
          rm -f .gitattributes

          # 3. Commit perubahan ini (Hanya terjadi di server sementara GitHub, repo aslimu AMAN)
          git add .
          git commit -m "Deploy: Backend only (Removed frontend images to satisfy HF)"

          # 4. Push ke Hugging Face
          git push https://FHQ360:$HF_TOKEN@huggingface.co/spaces/FHQ360/backend-quran-app main --force